version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: "123456"
    ports:
      - "27017:27017"
    volumes:
      - ./mongo_data:/data/db
    restart: always

  redis:
    image: redis:latest
    container_name: redis
    command: redis-server --requirepass "123456"
    ports:
      - "6379:6379"
    volumes:
      - ./redis_data:/data
    restart: always

  mysql:
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: "123456"
    ports:
      - "3306:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql
    restart: always